server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bmw_ssm?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: wxm147369
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:com/bmw/com.bmw.mapper/*Mapper.xml
  type-aliases-package: com.bmw.pojo