server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bmw_ssm?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: wxm147369
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.bmw.search.model
http:
  maxTotal: 300
  defaultMaxPerRoute: 50
  connectTimeout: 1000
  connectionRequestTimeout: 500
  socketTimeout: 5000
  staleConnectionCheckEnabled: true

redis: # Redis数据库索引（默认为0）
  database: '0'
  host: 192.168.48.101 # Redis服务器地址
  port: 6379  # Redis服务器连接端口
  password: 123456  #Redis服务器连接密码（默认为空）
  timeout: 1000 # 连接超时时间（毫秒）
  jedis:
    pool:
      max-active: 200  # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 10 # 连接池中的最大空闲连接
      min-idle: 0  # 连接池中的最小空闲连接