##normal##
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bmw_ssm?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: wxm147369
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.bmw.seed.model
data:
  showversion: version_dev
swagger:
  enable: true