##dev配置
server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://39.98.55.177:3306/bmw_ssm?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false
    username: deploy
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
data:
  showversion: version_pro